name: Create Mule Environments
on:
  workflow_dispatch:

jobs:
  createEnvironments:
    runs-on: ubuntu-latest
    steps:
    - name: Set Secrets
      env:
        GH_TOKEN: ${{ secrets.GON_GITHUB_TOKEN }}
      run:  gh secret set MYSECRET --body GonGon
